language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "8.9.1"
before_script: yarn add react@^16.2.0 react-dom@^16.2.0 prop-types@~15.5.8 --peer
after_success: yarn run coverage
after_script: yarn run coveralls
